/**
 * build-tokens.mjs — compiles DTCG token JSON into src/styles/tokens.css
 *
 * tokens/color.dark.json  → :root
 * tokens/color.light.json → html[data-theme="light"]
 * tokens/base.json        → :root (theme-independent)
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const readJson = async (p) => JSON.parse(await readFile(join(root, p), 'utf8'));

/** Flatten a DTCG group into [name, cssValue] pairs. */
function flatten(group, prefix = []) {
  const out = [];
  for (const [key, node] of Object.entries(group)) {
    if (key.startsWith('$')) continue;
    if (node && typeof node === 'object' && '$value' in node) {
      out.push([[...prefix, key].join('-'), toCss(node)]);
    } else if (node && typeof node === 'object') {
      out.push(...flatten(node, [...prefix, key]));
    }
  }
  return out;
}

function toCss(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'fontFamily':
      return v.map((f) => (f.includes(' ') ? `'${f}'` : f)).join(', ');
    case 'cubicBezier':
      return `cubic-bezier(${v.join(', ')})`;
    default:
      return String(v);
  }
}

const [dark, light, base] = await Promise.all([
  readJson('tokens/color.dark.json'),
  readJson('tokens/color.light.json'),
  readJson('tokens/base.json'),
]);

const block = (pairs, indent = '  ') =>
  pairs.map(([n, v]) => `${indent}--folio-${n}: ${v};`).join('\n');

const css = `/* Generated by scripts/build-tokens.mjs — DO NOT EDIT BY HAND.
 * Source of truth: tokens/*.json (DTCG format).
 * Folio DS — Swiss-style design tokens. Dark is the default theme. */

:root {
${block(flatten(dark))}

${block(flatten(base))}

  /* Composite shorthands */
  --folio-transition: var(--folio-motion-duration-base) var(--folio-motion-ease-out-expo);
  --folio-transition-fast: var(--folio-motion-duration-fast) var(--folio-motion-ease-out-expo);

  color-scheme: dark;
}

html[data-theme='light'] {
${block(flatten(light))}

  color-scheme: light;
}
`;

await mkdir(join(root, 'src/styles'), { recursive: true });
await writeFile(join(root, 'src/styles/tokens.css'), css);
console.log(`tokens.css written (${flatten(dark).length + flatten(base).length} tokens).`);
